version: "3.8"

services:
  bot:
    build: .
    container_name: discord-bot
    env_file: .env
    depends_on:
      - db
    restart: always
    networks:
      - botnet

  db:
    image: postgres:15
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DATABASE}
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - botnet

volumes:
  postgres-data:

networks:
  botnet:
